services:

  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: ${DB_PASSWORD}
      APP_USER: ${DB_USERNAME}
      APP_USER_PASSWORD: ${DB_PASSWORD}
    volumes:
      - oracle_data:/opt/oracle/oradata
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SELECT 1 FROM DUAL;' | sqlplus -s ${DB_USERNAME}/${DB_PASSWORD}@localhost:1521/FREEPDB1 > /dev/null"
        ]
      interval: 20s
      timeout: 10s
      retries: 30
      start_period: 240s

  meeting-decoder-api:
    build: .
    container_name: meeting-decoder-api
    ports:
      - "8080:8080"
    depends_on:
      oracle-db:
        condition: service_healthy
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: oracle-db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    restart: unless-stopped

volumes:
  oracle_data: