spring:
  application:
    name: meeting-decoder

  datasource:
    url: jdbc:oracle:thin:@//${DB_HOST:localhost}:${DB_PORT:1521}/${DB_NAME:FREEPDB1}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 60000
      validation-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update

    open-in-view: false
    show-sql: true

server:
  port: 8080

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE